import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./types`.

export type Workspace = Models.Row & {
  name: string;
  userId: string;
  image: string;
};
