import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./types`.

export type Workspace = Models.Row & {
  name: string;
  userId: string;
  imageId: string | null;
};

export type WorkspaceWithImageBlob = Workspace & {
  imageBlob: Blob | null;
};

export type WorkspaceWithImageUrl = Workspace & {
  imageUrl: string | null;
};
