namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_APPWRITE_PROJECT_ID: string;
    NEXT_PUBLIC_APPWRITE_PROJECT_NAME: string;
    NEXT_PUBLIC_APPWRITE_ENDPOINT: string;
    NEXT_APPWRITE_KEY: string;
    NEXT_PUBLIC_ORIGIN_URL: string;
    NEXT_PUBLIC_APPWRITE_DATABASE_ID: string;
    NEXT_PUBLIC_APPWRITE_WORKSPACES_ID: string;
    NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID: string;
  }
}
